feat(matrix): add role for LiveKit deployment
famedly/ansible-collection-matrix pull request #144
Opened 2024-08-19 11:00 UTC by blueorca363

2024-09-05 07:21 UTC, sebastian-de requested changes
Apart from that LGTM!

2024-09-05 07:21 UTC, sebastian-de commented on roles/livekit/README.md
> +  pre_tasks:
should be skipped - see my comment in your local PR.

2024-09-05 07:21 UTC, sebastian-de commented on roles/livekit/defaults/main.yml
> +  port: 7880
As mentioned in the local PR, ideally external ports should be made configurable (at least if it doesn't complicate the configuration too much).

2024-09-05 10:31 UTC, sebastian-de requested changes

2024-09-05 10:31 UTC, sebastian-de commented on roles/livekit/defaults/main.yml
> +livekit_turnserver_domain: "turn.dev.famedly.de"
```suggestion
livekit_turnserver_domain: ~
```

2024-09-05 10:34 UTC, blueorca363 commented on roles/livekit/defaults/main.yml
> +livekit_turnserver_domain: "turn.dev.famedly.de"
Done.

2024-09-05 10:52 UTC, sebastian-de requested changes
I'd name the commmit `feat(livekit): add role`

2024-09-06 06:38 UTC, sebastian-de approved these changes

2024-09-06 06:45 UTC, blueorca363 commented
/fast-forward

2024-09-06 06:46 UTC, merged